name: tourism_recommenders_environment
channels:
  - defaults
dependencies:
  - pip=22.3.1=py310hecd8cb5_0
  - python=3.10.9=h218abb5_0
  - pip:
      - gitpython==3.1.31
      - jsonschema==4.17.3
      - meteostat==1.6.5
      - numpy==1.24.2
      - pandas==1.5.3
      - requests==2.28.2
      - semver==2.13.0
      - streamlit==1.19.0
      - toml==0.10.2
